"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";

export default function WithdrawalFlow(){
 const router=useRouter();
 const [options,setOptions]=useState([]),[hasFundsPassword,setHasFundsPassword]=useState(null),[amount,setAmount]=useState(""),[password,setPassword]=useState(""),[newPass,setNewPass]=useState(""),[confirm,setConfirm]=useState("");
 const [policy,setPolicy]=useState(null),[identity,setIdentity]=useState(null),[govName,setGovName]=useState(""),[govId,setGovId]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){try{const [a,o,v]=await Promise.all([fetch('/api/account'),fetch('/api/withdrawal-options'),fetch('/api/account-security')]);const ad=await a.json(),od=await o.json(),vd=await v.json();if(a.ok)setHasFundsPassword(!!ad.account?.has_funds_password);if(o.ok){setOptions(od.amounts||[]);setPolicy(od);}if(v.ok){setIdentity(vd.verification||null);setGovName(vd.verification?.government_name||"");setGovId(vd.verification?.government_id_number||"");}}catch(e){setError("Unable to load withdrawal settings.")}}
 useEffect(()=>{load()},[]);
 async function savePassword(e){e.preventDefault();setError("");if(!/^\d{6}$/.test(newPass))return setError("Funds Password must contain exactly 6 numbers.");if(newPass!==confirm)return setError("Funds Passwords do not match.");setBusy(true);try{const r=await fetch('/api/funds-password',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fundsPassword:newPass})});const d=await r.json();if(!r.ok)throw new Error(d.error);setHasFundsPassword(true);setNewPass("");setConfirm("");}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function saveIdentity(e){e.preventDefault();setError("");if(!govName.trim()||!govId.trim())return setError("Government name and ID number are required.");setBusy(true);try{const r=await fetch('/api/account-security',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({governmentName:govName,idNumber:govId})});const d=await r.json();if(!r.ok)throw new Error(d.error);setIdentity(d.verification);setError("");}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function submit(e){e.preventDefault();setError("");setBusy(true);try{const r=await fetch('/api/withdrawals',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({amount,fundsPassword:password})});const d=await r.json();if(!r.ok)throw new Error(d.error);setPassword("");router.refresh();alert(`Withdrawal submitted. Reference: WD-${d.order.id}`)}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(hasFundsPassword===false)return <section className="admin-card"><div className="admin-card-head"><strong>Create Funds Password</strong><span className="badge">First-time setup</span></div><p className="muted">Create a 6-digit numeric Funds Password before you can request a withdrawal. It is stored securely and is never shown to Admin.</p><form className="form-card" onSubmit={savePassword}><label>Funds Password<input value={newPass} onChange={e=>setNewPass(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" maxLength={6} type="password" placeholder="6 numbers"/></label><label>Confirm Funds Password<input value={confirm} onChange={e=>setConfirm(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" maxLength={6} type="password" placeholder="Repeat 6 numbers"/></label>{error&&<p className="auth-error">{error}</p>}<button type="submit" className="primary-button" disabled={busy}>{busy?'Saving…':'Save Funds Password'}</button></form></section>;
 if(identity?.status!=='approved')return <section className="admin-card"><div className="admin-card-head"><strong>Complete Account Security</strong><span className="badge">Required before withdrawal</span></div><p className="muted">Enter your government/legal name and ID number. Admin must approve the verification before withdrawals are activated.</p>{identity?.status==='pending'&&<p className="muted"><strong>Status: Pending review.</strong> You can update the information below if needed.</p>}{identity?.status==='rejected'&&<p className="auth-error">Verification was rejected. Please correct your details and submit again.</p>}<form className="form-card" onSubmit={saveIdentity}><label>Government / Legal Name<input value={govName} onChange={e=>setGovName(e.target.value)} required/></label><label>Government ID Number<input value={govId} onChange={e=>setGovId(e.target.value)} required/></label>{error&&<p className="auth-error">{error}</p>}<button className="primary-button" type="submit" disabled={busy}>{busy?'Submitting…':'Submit for Verification'}</button></form></section>;
 const selected=Number(amount||0); const feeValue=policy?.feeMode==='fixed'?Number(policy?.feeValue||0):selected*Number(policy?.feeValue||0)/100; const net=Math.max(0,selected-feeValue);
 return <><form className="form-card" onSubmit={submit}><label>Choose amount</label><div className="amount-grid">{options.map(v=><button type="button" className={`amount-choice ${String(v)===String(amount)?'selected':''}`} key={v} onClick={()=>setAmount(String(v))}>GHS {Number(v).toLocaleString()}</button>)}</div>{!options.length&&<p className="muted">No withdrawal amounts are currently configured by Admin.</p>}<label>Funds Password<input value={password} onChange={e=>setPassword(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" maxLength={6} type="password" placeholder="6 numbers"/></label><div className="service-row"><span>Service charge</span><strong>GHS {feeValue.toFixed(2)}</strong></div><div className="service-row"><span>You receive</span><strong>GHS {net.toFixed(2)}</strong></div>{!policy?.allowed&&policy?.reason&&<p className="auth-error">{policy.reason}</p>}{error&&<p className="auth-error">{error}</p>}<button type="submit" className="primary-button" disabled={busy||!amount||password.length!==6||policy?.allowed!==true}>{busy?'Submitting…':'Submit Withdrawal'}</button></form><p className="muted">Processing time: {policy?.processingMinHours??0}–{policy?.processingMaxHours??48} hours.</p></>;
}
