"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

export default function Funds(){
 const [products,setProducts]=useState([]),[amounts,setAmounts]=useState({}),[status,setStatus]=useState(""),[busy,setBusy]=useState("");
 useEffect(()=>{fetch('/api/fund-products',{cache:'no-store'}).then(r=>r.json()).then(d=>setProducts(d.products||[])).catch(e=>setStatus(e.message));},[]);
 const calculations=useMemo(()=>Object.fromEntries(products.map(p=>{const a=Number(amounts[p.id]),r=Number(p.interest_rate);if(!Number.isFinite(a)||a<=0||!Number.isFinite(r))return [p.id,null];const interest=Math.round(a*r)/100;return [p.id,{interest,maturity:a+interest}]})),[amounts,products]);
 async function buy(product){const calc=calculations[product.id];if(!calc)return setStatus(`Enter a valid amount for ${product.name}.`);if(calc.maturity<=0)return;if(!window.confirm(`Are you sure you wish to proceed with ${product.name}?`))return;setBusy(String(product.id));setStatus('');try{const r=await fetch('/api/fund-products',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({productId:product.id,amount:amounts[product.id]})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Purchase failed.');setStatus(`${product.name} purchase successful. Your purchase is now in progress.`);setAmounts(x=>({...x,[product.id]:''}));}catch(e){setStatus(e.message)}finally{setBusy('')}}
 return <main className="mobile-shell scroll-page"><header className="topbar"><div><div className="eyebrow">Global Nexus Capital</div><h1>Fund Products</h1><p className="muted">Choose a fund and view its configured return</p></div><Link className="icon-button" href="/mine">←</Link></header>
 <section className="admin-card"><div className="admin-card-head"><strong>Available Funds</strong><span className="badge">{products.length}</span></div>
 {products.length===0?<p className="muted">No active fund products are currently available.</p>:<div style={{display:'grid',gap:16}}>{products.map(p=>{const calc=calculations[p.id];return <article key={p.id} className="form-card" style={{margin:0}}>{p.image_url&&<img src={p.image_url} alt={p.name} style={{width:'100%',maxHeight:220,objectFit:'cover',borderRadius:16,marginBottom:12}}/>}<div className="admin-card-head"><div><strong>{p.name}</strong><div className="muted">{p.interest_rate}% return · {p.period_days} days</div></div><span className="badge">Active</span></div>{p.description&&<p className="muted">{p.description}</p>}<p className="muted">Allowed amount: GHS {Number(p.min_purchase).toLocaleString()}–{p.max_purchase==null?'no maximum':`GHS ${Number(p.max_purchase).toLocaleString()}`}</p><label>Buy Amount<input inputMode="decimal" value={amounts[p.id]||''} onChange={e=>setAmounts(x=>({...x,[p.id]:e.target.value}))} placeholder="Enter amount"/></label><div className="return-box"><span>Interest</span><strong>{calc?`GHS ${calc.interest.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`:'—'}</strong></div><div className="return-box"><span>Amount to receive at maturity</span><strong>{calc?`GHS ${calc.maturity.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`:'—'}</strong></div><button type="button" className="primary-button" onClick={()=>buy(p)} disabled={busy===String(p.id)||!calc}>{busy===String(p.id)?'Processing…':'PAY'}</button></article>})}</div>}{status&&<p className="muted">{status}</p>}</section><section className="admin-card"><strong>My Fund Purchases</strong><div className="empty-document"><span>Active and matured fund records will appear here.</span></div></section></main>
}
